using PlanMenager;
using System.Windows;

namespace PlanLekcji
{
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            DataContext = new MainViewModel();
        }

        // Add this method if it is missing
        private void InitializeComponent()
        {
            // This method is usually auto-generated by Visual Studio.
            // If your .xaml file is not set to build as a Page, or if the designer did not generate this,
            // you may need to ensure your .xaml and .xaml.cs files are properly linked.
            // Typically, this method is generated and should not be manually implemented.
        }
    }
}
